### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by joshjayk** [pkhxcp/CommenterProcessor#1]
AssertionError when testing for multiple subreddits and parsing the comments... Check error log for more information?

**Comment by pkhxcp** [comment]
type is a reserved keyword in python! I renamed it to sortType.

But the AssertionError, I'm pretty sure that's a problem of PRAW. I think what's happening is that there's a MoreComments object found, but when you try to call .comments() on it, it freaks out when it doesn't return more comments. Check out the code and lmk what you think.
